### PR TITLE
FIX:  The esm template does not employ the ts template's db and server connection method/approach yet

### LINKED ISSUE #12: The esm template does not employ the ts template's db and server connection method/approach yet
#### Issue description
The esm template does not employ the ts template's db and server connection method/approach yet. The ts approach is straightforward and better structured.

#### Steps to reproduce the issue
1. Go to https://github.com/code-collabo/node-mongo-api-boilerplate-templates
2. Compare esm template's db and server files to that of the ts template
3. You will see that the ts template uses a more structured approach in the way the db and server is connected

#### Expected behavior
The esm template should use the mongooseConnect() and mongooseAtlasConnect() functions where necessary, and adopt the file names, in order to look consistent with the ts template. 

#### Screenshots
None

#### Additional context
None

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for. 
- [ ] mongooseConnect() function is now added and used in the esm template, just as it is used in the ts template
- [ ] mongooseAtlasConnect() function is now added and used in the esm template, just as it is used in the ts template
- [ ] all db and server files  in the esm template now adopt the file names as used in the ts template
- [ ] No new code or functionality was added, I only made the esm template to employ the ts template's db and server connection method/approach
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by samuko-things**
**This pull request makes the following changes**
* Fixes code-collabo/node-mongo#12 

**General checklist**
- [x] File or folder now contains changes as specified in the issue i worked on
- [x] I have linked the issue I worked on to this pull request submitted by me

**Testing checklist**
- [x] mongooseConnect() function is now added and used in the esm template, just as it is used in the ts template
- [x] mongooseAtlasConnect() function is now added and used in the esm template, just as it is used in the ts template
- [x] all db and server files in the esm template now adopt the file names as used in the ts template
- [x] No new code or functionality was added, I only made the esm template to employ the ts template's db and server connection method/approach
- [x] I certify that I ran my checklist

Ping @code-collabo/node-mongo

### CODE REVIEW

**Comment by samuko-things** [comment]
@Ifycode, I have just restructured the esm template db connection to replicate that of the esm template. do check it out. my only problem is how to edit the package.json file to fit the changes

File: esm/src/server.js [hunk 1]
```diff
@@ -1,16 +1,8 @@
...
-
-server.listen(port, () => {
-  try {
-    console.log( chalk.cyanBright(`\nServer running at http://localhost:${port}`) );
-  }catch(err) {
-    console.log(err);
-  }
+app.listen(port, () => {
+  mongooseConnect(port);
 });
```
Comment (Ifycode) [inline esm/src/server.js:8]: Nice work @samuko-things. I see you have the latest changes which make my ongoing clean-up work easier 👍🏽

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: esm/src/server.js (hunk 1 above)
Comment (Ifycode) [reply esm/src/server.js:8]: @samuko-things Please also note the following for the esm template:
- It should also have the .example.env file
- Use the `dev` and `dev:atlas` approach in the package.json file, that way, you will be able to test if it works without issues.

#

> **Note**
> Do these for the cjs template when you submit a PR for it

Comment (Ifycode) [reply esm/src/server.js:8]: @samuko-things Please also note the following for the esm template:
- It should also have the .example.env file (You can copy the content of the new .example.env file into your own .env file).
- Use the `dev` and `dev:atlas` approach in the package.json file

That way, you will be able to test if it works without issues.

#

> **Note**
> Do these for the cjs template when you submit a PR for it

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: esm/src/server.js (hunk 1 above)
Comment (Ifycode) [reply esm/src/server.js:8]: @samuko-things Please also note the following for the esm template:
- It should also have the .example.env file (You can copy the content of the new .example.env file into your own .env file).
- Use the `dev` and `dev:atlas` approach in the package.json file

That way, you will be able to test if it works without issues.

#

> **Note**
> Do these for the cjs template when you submit a PR for it

Comment (Ifycode) [reply esm/src/server.js:8]: OK. Sorry @samuko-things I did not see the part where you talked about your confusion with package.json file earlier. 

This was what was there previously:

````
"start": "nodemon --exec npm-run-all --parallel open:src lint:watch",
"open:src": "babel-node src/server.js",
````
#

What to change it to... 

1. You have to kind of divide `open:src` into local and atlas first like so:

````
"open:src:local": "babel-node path/to/local/server/here",
"open:src:atlas": "babel-node path/to/atlas/server/here"
````

2. Then divide `start` into `dev` and `dev:atlas` like so:
````
"dev": "nodemon --exec open:src:local",
"dev:atlas": "nodemon --exec open:src:atlas"
````

# 

> **Note**
> - If you notice, we now have a function EslintWatch() somewhere else in the code that takes care of running our lint:watch command. So that's why I no longer added it in the dev or dev:atlas line my code snippet.
> - We also do not need npm-run-all package any more. It helped us to run 2 npm scripts together before, now that we are running Eslint watch from somewhere else, you can safely **uninstall the npm-run-all package**. This is also why I no longer included it too in my code snippet.

#
That said, I think it's shorter and easier to just do it straight like this, and remove the open:src complexity:

````
"dev": "nodemon --exec babel-node path/to/local/server/here",
"dev:atlas": "nodemon --exec babel-node path/to/atlas/server/here"
````

> **Note**
> I can't remember if it's `nodemon - - exec` or just `nodemon` when not using npm-run-all. Just experiment. And let me know if you have any issues while doing so.

**Comment by samuko-things** [comment]
i have updated the package.json file as suggested. please do check it out

File: esm/src/server.js (hunk 1 above)
Comment (Ifycode) [inline esm/src/server.js:8]: Thank you @samuko-things 
Approving and sending over to a cleanup branch for further cleanup and testing

**Review by Ifycode — APPROVED** [review]
