### PR TITLE
FIX: The esm template does not use MVC architecture pattern (and modern js syntax) yet

### LINKED ISSUE #7: The esm template does not use MVC architecture pattern (and modern js syntax) yet
#### Issue description
The esm template does not use the MVC architecture pattern yet i.e. Models, routes, services and controllers code are not yet separated into respective files. It makes it hard to read, and also hard to see similarities between the other 2 templates.
In addition, .then() syntax is used for promises instead of the more recent async/await syntax. 
Regular functions are also used instead of the arrow function syntax. 

#### Steps to reproduce the issue
1. Go to https://github.com/code-collabo/node-mongo-api-boilerplate-templates
2. Compare esm template's api folder content with that of ts template.
3. You will see that the ts template uses the MVC architecture successfully, also uses the async/await syntax to work with promises and arrow functions. 

#### Expected behavior
The esm template should use the MVC architecture, the async/await syntax and arrow functions, in order to look consistent with the ts template. 

#### Screenshots
None

#### Additional context
None

#### Testing checklist
Note: Add the testing checklist below (without this note) to your pull request when submitting your fix. This will guide (you and) the contributors who will review your fix to know what is important to check or test for. 
- [ ] all GET, POST, PATCH, PUT and DELETE requests have been restructed to use MVC: Models, routes, services and controllers are separated and in different files.
- [ ] async/await syntax now used everywhere instead of .then()
- [ ] Arrow functions are now used instead of Regular functions
- [ ] The function names and variable names are same as the ones found in the routes, controllers and services files of the ts template.
- [ ] No new code or functionality was added, I only restructured existing code to use MVC pattern and added newer js syntax.
- [ ] I certify that I ran my checklist

### PR DESCRIPTION
**Pull request by samuko-things**
**This pull request makes the following changes:**
* Fixes code-collabo/node-mongo#7

**General checklist**
- [x] all GET, POST, PATCH, PUT and DELETE requests have been restructed to use MVC: Models, routes, services and controllers are separated and in different files.
- [x] async/await syntax now used everywhere instead of .then()
- [x] Arrow functions are now used instead of Regular functions
- [x] The function names and variable names are same as the ones found in the routes, controllers and services files of the ts template.
- [x] No new code or functionality was added, I only restructured existing code to use MVC pattern and added newer js syntax.
- [x] I certify that I ran my checklist

Ping @code-collabo/node-mongo

### CODE REVIEW

**Comment by samuko-things** [comment]
i have just restructured the esm api template. do check it out

File: esm/src/api/controllers/demo.controller.js [hunk 1]
```diff
@@ -0,0 +1,221 @@
...
+//       });
+//     })
+//     .catch((err) => {
+//       res.status(500).json({
+//         message: `Error updating ${item}`,
+//         error: `${err}`,
+//       });
+//       console.log(chalk.redBright(`\nError updating ${item}: ${err}\n`));
+//     });
+// });
```
Comment (Ifycode) [inline esm/src/api/controllers/demo.controller.js]: @samuko-things Nice work. I haven't tested that it works yet. But you should also restructure patch and put to mvc too.

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: esm/src/api/controllers/demo.controller.js (hunk 1 above)
Comment (Ifycode) [reply esm/src/api/controllers/demo.controller.js]: Also note: 
- The space before the #8 does not make it link your PR to the issue properly. Please link the issue

**Comment by samuko-things** [comment]
i've just restructured the patch and put, do check it out.

File: esm/src/api/controllers/demo.controller.js [hunk 2]
```diff
@@ -0,0 +1,201 @@
...
+  } catch (err) {
+    res.status(500).json({
+      message: `Error deleting ${item}`,
+      error: `${err}`,
+    });
+    console.log(chalk.redBright(`\nError deleting ${item}: ${err}\n`));
+  }
+};
+
+const partialUpdateDemoItemController = async (req, res, next) => {
```
Comment (Ifycode) [inline esm/src/api/controllers/demo.controller.js]: ### Review comment 1
#
Nice work @samuko-things 

"partialUpdate" is a bit general. It will be better to be more specific.

If you notice in the service we are interacting with the database using the `Demo.updateOne()` method.
So it will be better to replace `partialUpdateDemoItemController` with `updateOneDemoItemPropertyValueController` in the function name(s).

(also remember to do this for services, routes and any other place you used "partialUpdate")

It will help the dev using it to quickly know what the function does just by looking at the function name without thinking too much.
These questions should give insight to why it's better to so this:
- What is being updated? => "propertyValue"
- How many of it are we updating? => "updateOne"

Youtube video reference (for patch request updating just one): https://youtu.be/WDrU305J1yw?t=1855

**Review by Ifycode — CHANGES_REQUESTED** [review]

File: esm/src/api/controllers/demo.controller.js [hunk 3]
```diff
@@ -0,0 +1,201 @@
...
+      error: `${err}`,
+    });
+    console.log(
+      chalk.redBright(`\nError updating ${item} property & value: ${err}\n`)
+    );
+  }
+};
+
+
+const fullUpdateDemoItemController = async (req, res) => {
```
Comment (Ifycode) [inline esm/src/api/controllers/demo.controller.js]: ### Review comment 2
#
Do the same thing I suggested for patch for put too @samuko-things

But this time the name should be `updateDemoItemPropertyValuesController`

Emphasis on "update" and plural of "PropertyValues" in the new name.

(also remember to do this for services, routes and any other place you used "fullUpdate")

Comment (Ifycode) [reply esm/src/api/controllers/demo.controller.js]: ### Review comment 3
#

Make PATCH request code come after PUT (everywhere)

**Review by Ifycode — CHANGES_REQUESTED** [review]

**Comment by samuko-things** [comment]
i have renamed the patch and pull function as requested. do check it out

**Comment by samuko-things** [comment]
i have updated the esm templated as requested. do check it out.

**Comment by samuko-things** [comment]
@Ifycode, i have also tested the esm template and it works. Although it has a few errors and warnings with does not come from the restructuring

**Comment by Ifycode** [comment]
Thank you @samuko-things
I will check it out.
But I can't do that until you have corrected the prettier mess in the ts template PR. Once you have done that, I will review all 3 PRs submitted so far.

**Review by Ifycode — APPROVED** [review]
